### ISSUE TITLE
bug: installing with fisher does not work

### ISSUE THREAD

**Issue by kunzaatko** [paldepind/projectdo#9]
The `projectdo` script is not in functions. The `README.md` should probably tell users to add the script into their `$PATH`

**Comment by paldepind** [comment]
Yeah. One has to install both `projectdo` and then the Fish plugin. Do you think this should be made more clear in the readme?

**Comment by kunzaatko** [comment]
Yeah... I think only people that are familiar with the fish plugin ecosystem would know that this is necessary...
It becomes obvious, once you try to use it without the binary, but a note in the README never hurts :)

**Comment by kunzaatko** [comment]
Checkout if this would be fine by you
